### ISSUE TITLE
Is this ready for public consumption yet?

### ISSUE THREAD

**Issue by spiritualgeek** [mnadel/freddiebear#1]
**_/Users/mikenadel/Projects/go/bin/freddiebear_**

```[14:28:17.588] ERROR: Freddiebear[Script Filter] Code 127: zsh:1: no such file or directory: /Users/mikenadel/Projects/go/bin/freddiebear
[14:28:17.892] Freddiebear[Script Filter] Queuing argument 'mv'
[14:28:17.899] Freddiebear[Script Filter] Script with argv '(null)' finished```

**Comment by mnadel** [comment]
Sorry, just saw this. Happy to fix, what's up?

**Comment by spiritualgeek** [comment]
Seems like your workflow is trying to invoke something in `/Users/mikenadel/Projects/go/bin` which does not exist

**Comment by mnadel** [comment]
Ah! Just pushed a new version that moved that hidden config to the workflow configuration:

<img width="593" alt="image" src="https://github.com/mnadel/freddiebear/assets/1819618/e99824fb-d542-4251-965b-3fb11781f279">
